NumPy Functions numpy tricks


np.sort(array , axis,kind)
Returns a sorted copy of an array


In [5]:
import numpy as np
a = np.random.randint(1,100,15)
np.sort(a) ## returns a sorted copy, for descending order is t
np.sort(a)[::-1]

array([15, 21, 36, 37, 46, 52, 57, 64, 64, 70, 72, 78, 81, 83, 99],
      dtype=int32)

In [11]:
b = np.random.randint(1,100,24).reshape(6,4)
np.sort(b,axis = 0) # column wise sorting

array([[12,  8, 29, 20],
       [47, 14, 37, 28],
       [49, 51, 38, 30],
       [66, 71, 47, 52],
       [66, 73, 55, 66],
       [77, 75, 93, 98]], dtype=int32)

np.append
The nupy.append() appends values along the mentioned axis at the end of the array

In [8]:
import numpy as np
arr1 = np.random.randint(1,11,5)
np.append(arr1,80) # takes two parameters, one is the array and second is the value to be appended


array([ 5,  6,  1,  5,  2, 80])

In [29]:
## Assume we have a 2D array, and we have to append an entire column, at the end
# here we have an array of shape(6,4) and we are defining a new variable which is
## new_col as we have to append all ones then we use np.ones() here we pass the shape in form of a tuple(6,1)
## and then we are appending it to the existing array
# Axis means: what stays the same
# axis = 1
#
# Rows stay the same
#
# Columns change (increase)
# ✅ This is exactly what we want
#
# axis = 0
#
# Columns stay the same
#
# Rows change (increase)
import numpy as np
b = np.random.randint(1, 100, 24).reshape(6, 4)
new_col = np.ones((6, 1))   # column with same number of rows
b = np.append(b, new_col, axis=1) # and we need to append it
print(b)


[[28. 42. 93. 31.  1.]
 [ 5. 13. 35. 11.  1.]
 [53. 65.  7. 43.  1.]
 [65. 74. 87. 40.  1.]
 [72.  2. 40. 82.  1.]
 [98. 64. 61. 64.  1.]]


np.concatenate() function concatenate a sequence of arrays along an existing axis

In [30]:
# Similar to vstack and hstack functions

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

print(np.concatenate((c,d),axis=1)) # row wise concatenation axis = 1

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


##### np.unique
with the help of np.unique() method we can get the unique values from an array given as parameter in np.unique() method

In [33]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6]) # repeated elements are present in the array
np.unique(e) # returns all the unique items, very beneficial functions

array([1, 2, 3, 4, 5, 6])

##### np.expand_dims
with the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array
Eg: conversion of one dimension to two dimension

In [62]:
# code
# 🎯 The ONE Rule for expand_dims
# axis tells you the POSITION (index) in the new shape tuple where you insert a 1
# That's it! Simple as that.
arr = np.random.randint(1,100,20)
print(arr.ndim) # 1-D array

1


In [67]:
np.expand_dims(arr,axis=0).ndim # using expand_dims converted to 2-D, and we are expanding across

2

In [68]:
np.expand_dims(arr,axis=1)

array([[87],
       [60],
       [17],
       [48],
       [ 9],
       [57],
       [23],
       [94],
       [ 9],
       [62],
       [40],
       [43],
       [12],
       [25],
       [74],
       [28],
       [43],
       [99],
       [63],
       [44]], dtype=int32)

In [9]:
import numpy as np
## What exactly is expanding the dimension
## using expand_dims( parameter1 , parameter 2) we give two parameters here
## 1. actual array 2. axis
## whatever value of axis we provide in the parameter at that particular index
## our dimension will get added, and we know how to read the output of .shape() function
## it also works with negative indexing
"""
axis = -1  →  means "last position" (end)
axis = -2  →  means "second to last position"
axis = -3  →  means "third to last position"
etc.
"""

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print('Array',arr)
print(arr.shape)
## Expand a dimension along the axis 0 == Add 1 to the index 0
## Expand a dimension along the axis 1 == Add 1 at the index 1 position
## evaluated output: (1,2,4) where 1 = block, 2 = rows per block , 4 = columns

print(np.expand_dims(arr,axis=0).shape)

Array [[1 2 3 4]
 [5 6 7 8]]
(2, 4)
(1, 2, 4)


##### np.where
The numpy.where() functions returns the indices of elements in an input array where the given condition is satisfied

In [80]:
arr

array([87, 60, 17, 48,  9, 57, 23, 94,  9, 62, 40, 43, 12, 25, 74, 28, 43,
       99, 63, 44], dtype=int32)

In [81]:
## find all indices with value greater than 50, index not values
np.where(arr>50) # returns tuple of indices where the numbers are greater than 50

(array([ 0,  1,  5,  7,  9, 14, 17, 18]),)

In [83]:
## replace all values > 50 with 0
# np.where(condition,true,false)

np.where(arr>50,0,arr) ## condition is values>50, if condition true then replace those values with 0, else as it is

array([ 0,  0, 17, 48,  9,  0, 23,  0,  9,  0, 40, 43, 12, 25,  0, 28, 43,
        0,  0, 44], dtype=int32)

##### np.argmax
The np.argmax() function returns indices of the max element of the array in a particular axis
(kisi bhi axis me jo bhi max element hai uska index extract karne ka tarika)

In [25]:
a = np.random.randint(1,100,15)
print(a)
print(np.argmax(a)) # 99 largest among all which is at index position 9
# To find the index of the max element from the array, normal np.max() returns the actual value, but argmax returns the index


b = np.random.randint(1,100,24).reshape(4,6)
print(b)
print(np.argmax(b,axis = 0)) # we can also mention the axis to know the max index along the row

[11 43 65 15 66 80 62 59 37 99 54 43 26 98 54]
9
[[85 33  6 44 87 71]
 [70 44 49  4 79 72]
 [29 95 52 35 42 23]
 [96 98 42  5 33 12]]
[3 3 2 0 0 1]


##### np.argmin()
The np.argmax() function returns indices of the min element of the array in a particular axis (kisi bhi axis me jo bhi min element hai uska index extract karne ka tarika)


In [27]:
print(a)
print(np.argmin(a)) # 11 is the min element at index 0

## Opposite of np.argmax()

[11 43 65 15 66 80 62 59 37 99 54 43 26 98 54]
0


In [ ]:
"""
##### np.cumsum()
It is used when we want to compute the cumulative sum of array elements over a given axis
Example: Data about a batsman scores in matches 25,56,89,25,100 in first match second third etc
To find: Find the total career runs

25
25+56
25+56+89
25+56+89+25
25+56+89+25+100

"""

In [29]:
print(np.cumsum(a))

[ 11  54 119 134 200 280 342 401 438 537 591 634 660 758 812]


In [32]:
print(b)
print()
print(np.cumsum(b)) # if we don't mention the axis then, it converts the array to 1D and does the sum
print()
print(np.cumsum(b,axis = 0)) # evaluating the cumulative sum row wise

[[85 33  6 44 87 71]
 [70 44 49  4 79 72]
 [29 95 52 35 42 23]
 [96 98 42  5 33 12]]

[  85  118  124  168  255  326  396  440  489  493  572  644  673  768
  820  855  897  920 1016 1114 1156 1161 1194 1206]

[[ 85  33   6  44  87  71]
 [155  77  55  48 166 143]
 [184 172 107  83 208 166]
 [280 270 149  88 241 178]]


##### np.cumprod
cumulative product
similar to the cumulative sum just evaluates the multiplication

25

25*56

25*56*89

25*56*89*25

25*56*89*25*100

In [40]:
arr = np.arange(1,6)
print(arr)
print(np.cumprod(arr))

[1 2 3 4 5]
[  1   2   6  24 120]


##### np.percentile
Used to compute the  nth percentile of the given data (array elements) along the specified axis.

In [43]:
print(a)
print(np.percentile(a,100))
print(np.percentile(a,0))
print(np.percentile(a,50))

[11 43 65 15 66 80 62 59 37 99 54 43 26 98 54]
99.0
11.0
54.0


##### np.histogram()
Numpy has a built in numpy.histogram() function which represent the frequency of data distribution in the graphical form

Example: Let say we have data as 5,15,9,17,25,23,29, and we have the bin size of 0-10,11-20,21-30
0-10 -> (2,9) so frequency is 2

11-20 -> (15,17) frequency is 2

21-30 -> (25,23,29) frequency is 3

Bars are plotted based on the frequency


In [5]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)

np.histogram(a,bins = [0,10,20,30,40,50,60,70,80,90,100])

[36 45  5 29 68 58  4 91 71 30 80 77 14 63 96]


(array([2, 1, 1, 2, 1, 1, 2, 2, 1, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

##### np.corrcoef
Return Pearson product-moment correlation coefficient

example:  correlation is always between -1 to 1
Consider we have two quantities x and y, x is experience, and y is salary , the value we get tells the correlation between the
two quantities if value is 0 -> It means no correlation , if correlation 1 it means that both the quantities are positively
correlated(if experience increases -> salary increases) if correlation is -1(if experience decrease -> salary decrease)

In [6]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)
## quantities relation with itself is 1

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

##### np.isin
with the help of numpy.isin() method , we can see that one array having values are checked in a different numpy array having
different elements with different size

use case: searching multiple items from an array simultaneously

In [19]:
array_num = np.arange(21)
items = [10,20,30,40,50,60,70,80,90,100]
print(array_num) ## actual array
print(np.isin(array_num,items)) # passed the array and the items to be searched simultaneously
## returns bool values True if present, False if absent
## here 10 and 20 are present so it prints True at index 10 and 20 respectively

## we can also use mask to get the actual values which are present instead of getting True
print(array_num[np.isin(array_num,items)] ) # converting it into mask which gives which elements are actually present

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[False False False False False False False False False False  True False
 False False False False False False False False  True]
[10 20]


##### np.flip()
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array

In [4]:
import numpy as np
arr_md = np.arange(20).reshape(5,4)
print(arr_md)
print()

print(np.flip(arr_md) )# 0th index goes at the last index and so on
print()
print(np.flip(arr_md,axis = 0)) # along the row the elements are flipped
print()
print(np.flip(arr_md,axis = 1)) # along the column the elements are flipped

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[19 18 17 16]
 [15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]

[[16 17 18 19]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]
 [19 18 17 16]]


##### np.put
The np.put() function replaces specific elements of an array with the given values of p_array. Array indexed works on flattend array


In [ ]:
## It is similar to replace function in python, but only for values of array, and we can do it for multiple numbers 
a = np.random.randint(1,100,15)
print(a) ## original array with random values
  

np.put(a,[0,1],[110,530]) ## first parameter = array, second parameter = index which need to be changed , third parameter = actual value to be replaced 
## this changes are inside the actual array 

print(a) # original array with replaced values at index 0 and 1 

[46 30 98 80 22 19 25 54 69 73 66 46 64 65 17]
[110 530  98  80  22  19  25  54  69  73  66  46  64  65  17]


##### np.delete()

The np.delete() function returns a new array with theh deletion of sub-arrays along with the mentioned axis

In [ ]:
import numpy as np

# Create 1D array
arr = np.array([10, 20, 30, 40, 50]) # original array

# Delete single element at index 2
result1 = np.delete(arr, 2) # 30 deleted
print(result1)  # [10 20 40 50]

# Delete multiple elements
result2 = np.delete(arr, [0, 3])
print(result2)  # [20 30 50]

# Delete using slice
result3 = np.delete(arr, slice(1, 4))
print(result3)  # [10 50]

[10 20 40 50]
[20 30 50]
[10 50]


In [15]:
import numpy as np

# Create 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Delete row (axis=0)
result1 = np.delete(arr, 1, axis=0)  # Delete row at index 1
print(result1)
# [[1 2 3]
#  [7 8 9]]

# Delete column (axis=1)
result2 = np.delete(arr, 2, axis=1)  # Delete column at index 2
print(result2)
# [[1 2]
#  [4 5]
#  [7 8]]

# Delete multiple rows
result3 = np.delete(arr, [0, 2], axis=0)
print(result3)
# [[4 5 6]]

# Delete multiple columns
result4 = np.delete(arr, [0, 1], axis=1)
print(result4)
# [[3]
#  [6]
#  [9]]

# Without axis (flattens then deletes)
result5 = np.delete(arr, [0, 4, 8])  # Deletes elements at these positions
print(result5)  # [2 3 4 6 7 9]

[[1 2 3]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[4 5 6]]
[[3]
 [6]
 [9]]
[2 3 4 6 7 8]


#### Set functions
1.np.union
2.np.intersect1d
3.np.setdiff1d
4.np.setxor1d
5.np.in1d

In [ ]:
## 1. np.union()
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n) # Return the unique, sorted array of values that are in either of the two input arrays.

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
## 2. np.intersect1d()
np.intersect1d(m,n) # Return the sorted, unique values that are in both of the input arrays

array([3, 4, 5])

In [ ]:
## 3. np.setdiff1d()
np.setdiff1d(m,n) # Return the sorted, unique values that are in the first array but not in the second

array([1, 2])

In [19]:
## 4. np.setxor1d()
np.setxor1d(m,n) # Return the sorted, unique values that are in exactly one of the two input arrays

array([1, 2, 6, 7])

##### np.clip()
np.clip() function is used to clip the values in an array
np.clip() is used to limit (clamp) values in an array to a specified range. Any value below the minimum becomes the minimum, and any value above the maximum becomes the maximum.

In [28]:
a 

array([110, 530,  98,  80,  22,  19,  25,  54,  69,  73,  66,  46,  64,
        65,  17], dtype=int32)

In [ ]:
np.clip(a,a_min = 25,a_max = 75) 

array([75, 75, 75, 75, 25, 25, 25, 54, 69, 73, 66, 46, 64, 65, 25],
      dtype=int32)