#### Numpy
numpy is a fundamental library for scientific computing in python. It provides support for
arrays and matrices, along with a collection of mathematical functions to operate on these
data structures.

In [ ]:
#### Creating numpy arrays
# 1. Using np.array()// 1-D and 2-D
# 2. Using np.zeroes/ones/empty/random()
# 3. Using np.arange()
# 4. Using np.linspace()
# 5. Using copy()
# 6. Using Identity()

In [11]:
## create numpy. n-d arrays
# we can also call it as a vector
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([[1,2,3],[4,5,6]]) # we can call this a matrix
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#dtype
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [22]:
np.array([1,2,3],dtype = bool)
# why it shows true is python treats non-zero values as 1 and 1 means True

array([ True,  True,  True])

In [13]:
# make sure we pass a tuple (values,values...)
arr3 = np.zeros((2,3)) # two rows three columns
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# we need to provide a tuple as a parameter in the function
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
arr5 = np.identity(5) # one is in the diagonals
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
arr6 = np.arange(5,16,2) # third parameter is for jumps, two parameters for just range
arr6

array([ 5,  7,  9, 11, 13, 15])

In [23]:
## arange with reshape
np.arange(1,11).reshape(5,2) # 5 rows and 2 columns , in reshape values we put , the product must be equal to the no of items
## we can also pass a third parameter in the reshape which is depth or number of "layers"

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
## np.random, between 0 and 1 ,it will provide random  values , it needs the (rows,cols) tuple as parameter
np.random.random((3,4))

array([[0.55681036, 0.74700378, 0.66133849, 0.00817377],
       [0.31921179, 0.40364934, 0.60586655, 0.01897492],
       [0.40483328, 0.72886477, 0.74130059, 0.58109456]])

In [26]:
## np.linspace or linear space
## used for graphs and plotting graphs

arr7 = np.linspace(10,20,10) # lower range , upper range , equidistance points
arr7

## step = (stop - start) / (num - 1)
# step = 10 / 9 ≈ 1.111


array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [27]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

#### Important attributes in numpy
1. Shape
2. nDim
3. Size
4. Itemsize
5. Dtype
6. astype()

In [28]:
arr1.shape

(6,)

In [29]:
arr2.shape

(2, 3)

In [37]:
arr9 = np.array([
    [[1,2],[3,4]]
    ,[[5,6],[7,9]]
])
print(arr9)
arr9.shape ### (2,2,2)

## how to check the shape
## there are two blocks
## in each block there are 2 rows
## and in each row there are three columns

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]


(2, 2, 2)

In [38]:
arr9.ndim # to check the dimension of the array

3

In [40]:
print(arr2.ndim)
print(arr1.ndim)

2
1


In [41]:
arr1.size # no of items are 6

6

In [45]:
arr8.itemsize # floating point occupy 8 bytes of memory location in memory, if integer then it is 4

8

In [46]:
## dtype shows the datatype of itemsft
arr8.dtype # datatype which is floating point


dtype('float64')

In [47]:
arr9.dtype

dtype('int64')

In [48]:
## convert the type of data in a numpy array
arr9.astype('float') # which ever datatype we pass as, it will convert the data into that datatype

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 9.]]])

#### Numpy Array vs Python list
1. Faster
2. convenient
3. less memory

In [55]:
## Memory

import sys
import numpy as np

lst1 = list(range(100))
arr11 = np.arange(100)

print(sys.getsizeof(lst1))           # Memory used by list
print(arr11.nbytes)                   # Memory used by numpy array

## Returns the total memory size (in bytes) of a Python object
## Returns the total bytes consumed by the data in a NumPy array.

856
800


In [66]:
## Faster operation
import time
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time() # gives the current time, before operation
c = [(x,y) for x,y in zip(x,y)]

print(time.time() - start_time)

1.2485544681549072


In [65]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start_time = time.time()
c = a+b # a's one item and b's one item
print(time.time() - start_time)

0.4589419364929199


#### Indexing ,Slicing and Iteration

In [6]:
import numpy as np
## using indexing we fetch only one item
## using slicing we fetch more than one item
arr12 =  np.arange(24).reshape(6,4) # we can reshape it based on the factors (8,3),(6,4),(12,2)
print(arr12)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [15]:
arr12[2:4,1:3] # we need to extract the 3,10,13,14


array([[ 9, 10],
       [13, 14]])

In [17]:
arr12[4:,2:] # we need to extract 18,19,22,23

array([[18, 19],
       [22, 23]])

In [19]:
for i in arr12: # prints row by row
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [35]:
my_arr = np.arange(8).reshape(2,2,2)
print(my_arr)
## fetching 5 from a3 tensor or 3d array

print(my_arr[1,0,1])
print(my_arr[0,0,0])
## we know  my_arr is 3D tensor, which is made from 2D array , so our 5 lies in which of the 2D array, it lies in the
## second one which has index 1, and then we check normal row and cols

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
0


In [20]:
# gives the items individually
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


#### Numpy array operations
Scalar and vector operations


In [25]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
## Scalar operations


a1*2 # we can call a1 as a matrix and 2 as a scalar, it will multiply 2 with each matrix item
## similarly we can do all arithmetic operations
# Basic arithmetic
a1 + 5      # Addition
a1 - 3      # Subtraction
a1 * 2      # Multiplication
a1 / 2      # Division
a1 // 2     # Floor division
a1 % 3      # Modulus (remainder)
a1 ** 2     # Exponentiation (power)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [28]:

## comparison operations
a2>5 # itemwise comparison , every number is greater than 5 so true, else False

## similarly we can perform
# a1 > 2      # Returns boolean array [False, False, True, True]
# a1 >= 2     # Greater than or equal
# a1 < 3      # Less than
# a1 == 2     # Equal to
# a1 != 2     # Not equal to


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### vector operations
when we apply a operation on two numpy arrays

In [3]:
import numpy as np


arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)

In [8]:
## vector operations
print(arr1 + arr2) # itemwise addition
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


##### Array Functions
 max/min/sum/prod

In [10]:
array1 = np.random.random((3,3))
array1 = np.round(array1*100)
print(array1)

[[30. 11. 44.]
 [73. 32. 82.]
 [18. 88. 98.]]


In [12]:
## max/min/sum/prod

print(np.max(array1)) # largest or max item in the array
print(np.min(array1))
print(np.sum(array1))
print(np.prod(array1))


98.0
11.0
476.0
431752200929280.0


In [17]:
## condition:  what if we want the minimum of each row
## 0 -> column and 1 -> row
print(np.max(array1,axis=0)) ## maximum element from each column
print(np.max(array1,axis=1)) ## maximum element from each row
print(np.min(array1,axis=0)) ## min element from each column
print(np.min(array1,axis=1)) ## min element from each row
print(np.sum(array1,axis=0)) ## sum of elements of the column
print(np.sum(array1,axis=1)) ## sum of row elements
print(np.prod(array1,axis=0))## product of the column elements
print(np.prod(array1,axis=1))## product of the row elements

[73. 88. 98.]
[44. 82. 98.]
[18. 11. 44.]
[11. 32. 18.]
[121. 131. 224.]
[ 85. 187. 204.]
[ 39420.  30976. 353584.]
[ 14520. 191552. 155232.]


In [20]:
## mean/median/std/var

## mean
print(np.mean(array1)) # mean of the entire matrix
print(np.mean(array1, axis=0)) # mean of the column elements of the matrix
print(np.mean(array1, axis=1))  # mean of the row elements of the matrix
print('-' * 40)
## median
print(np.median(array1))
print(np.median(array1, axis=0))
print(np.median(array1, axis=1))
print('-' * 40)
## std
print(np.std(array1))
print(np.std(array1, axis=0))
print(np.std(array1, axis=1))
print('-' * 40)
## var
print(np.var(array1))
print(np.var(array1, axis=0))
print(np.var(array1, axis=1))

52.888888888888886
[40.33333333 43.66666667 74.66666667]
[28.33333333 62.33333333 68.        ]
----------------------------------------
44.0
[30. 32. 82.]
[30. 73. 88.]
----------------------------------------
30.787603726335647
[23.61261433 32.49957265 22.64705034]
[13.52364185 21.76133166 35.59026084]
----------------------------------------
947.8765432098766
[ 557.55555556 1056.22222222  512.88888889]
[ 182.88888889  473.55555556 1266.66666667]


In [21]:
## trigonometric functions
# Function	Description
# np.sin(array1)	#sine
# np.cos(array1)	#cosine
# np.tan(array1)	#tangent
# np.arcsin(array1)	#inverse sine
# np.arccos(array1)	#inverse cosine
# np.arctan(array1)	#inverse tangent
# np.deg2rad(array1)	#degrees → radians
# np.rad2deg(array1)	#radians → degrees
np.sin(array1)

array([[-0.98803162, -0.99999021,  0.01770193],
       [-0.67677196,  0.55142668,  0.31322878],
       [-0.75098725,  0.0353983 , -0.57338187]])

In [23]:
## dot product:
""" Dot product: if we have a matrix which is (x1,y1)->(3,4) and (x2,y2)->(4,3) then we check if y1 and x2 matches
    if matches then the resultant matrix will be (x1,y2)

    Example: [1,2,3]⋅[4,5,6]=(1×4)+(2×5)+(3×6)=32

for the below example: [0x12 + 1x15 + 2x18 + 3x21 ] = 114  and similarly
 """
array2 = np.arange(12).reshape(3,4) # 3 rows and 4 cols
array3 = np.arange(12,24).reshape(4,3) # opposite 4 rows and 3 cols
print(array2)
print(array3)
np.dot(array2, array3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [28]:
## log and exponents
print(np.log(array1))
print()
print(np.exp(array1))

[[3.40119738 2.39789527 3.78418963]
 [4.29045944 3.4657359  4.40671925]
 [2.89037176 4.47733681 4.58496748]]

[[1.06864746e+13 5.98741417e+04 1.28516001e+19]
 [5.05239363e+31 7.89629602e+13 4.09399696e+35]
 [6.56599691e+07 1.65163625e+38 3.63797095e+42]]


In [32]:
import numpy as np

# Sample array
arr = np.array([1.2, 1.5, 1.7, 2.5, -1.2, -1.7])

# Rounding operations
rounded = np.round(arr)   # nearest integer (banker's rounding)
floored = np.floor(arr)   # always round down
ceiled  = np.ceil(arr)    # always round up

print("Original :", arr)
print("Round    :", rounded)
print("Floor    :", floored)
print("Ceil     :", ceiled)

Original : [ 1.2  1.5  1.7  2.5 -1.2 -1.7]
Round    : [ 1.  2.  2.  2. -1. -2.]
Floor    : [ 1.  1.  1.  2. -2. -2.]
Ceil     : [ 2.  2.  2.  3. -1. -1.]


In [37]:
# cook your dish here
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print('-'*30)
print(a2)
print('-'*30)
print(a3)
print('-'*30)

## fetch item 6 from a2 array or matrix
print(a2[1,2])
## fetch 11 from the matrix
print(a2[-1,-1])


## fetching 5 from a3 tensor or 3d array

print(a3[1][0,1])

## slicing
print(a1[2:5]) # fetching 2,3,4 from a1

print(a2[0,:]) # fetching only the first row
## we want the first row so 0, and we need all the cols so : to get it



## we need to fetch the third column
print(a2[:,2]) # fetching 2,6,10

## we need to fetch 5,6,9,10
print(a2[1:,1:3])

# we need to fetch 0,3,8,11
print(a2[::2,::3])

## we want to fetch 1,3,9,11
print(a2[::2,1::2])

## print 4 and 7
print(a2[1,0::3])

## print 123,567
print(a2[0:2,1:])

[0 1 2 3 4 5 6 7 8 9]
------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
------------------------------
6
11
5
[2 3 4]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [39]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [40]:
## fetch 9,10,11,12,13,14,15,16,17
print(a3[1]) # we are selecting the second block so at index 1


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [42]:
## fetch first and last matrix
print(a3[::2]) # we want all of it , just jump 2 step

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [43]:
# first 2D array : fetch the second row of it
print(a3[0,1,:]) # 0 because it belongs to the first matrix, 1 because row of the 1 index , and : because we need all columns

[3 4 5]


In [44]:
## second array's , first index column
print(a3[1,:,1])

[10 13 16]


In [45]:
## print or access 22,23,25,26
print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [46]:
## access 0,2,18,20
print(a3[::2,0,::2])

[[ 0  2]
 [18 20]]


In [50]:
### Iterating
print(a1)


for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [51]:
print(a2)
for i in a2:
    print(i) # it will print one row at a time

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [53]:
print(a3)
print('-'*20)
for i in a3:
    print(i) #each time a 2D array gets printed

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [55]:
for i in np.nditer(a3):
    print(i , end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 